apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sshd.fullname" . }}
  labels:
    {{- include "sshd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sshd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sshd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 22
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: 22
          readinessProbe:
            tcpSocket:
              port: 22
          volumeMounts:
            - mountPath: /root/.ssh/
              name: ssh-dir
            - mountPath: /etc/ssh/hostKeys/
              name: ssh-host-keys
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: ssh-dir
          secret:
            secretName: {{ .Values.sshSecretName }}
            defaultMode: 256
        - name: ssh-host-keys
          secret:
            secretName: {{ .Values.sshHostKeysSecretName }}
            defaultMode: 256
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
